from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


# ============================================================
# TYPES
# ============================================================

HazardType = Literal[
    "flood",
    "earthquake",
]


RequestPriority = Literal[
    "low",
    "moderate",
    "high",
    "critical",
]


RequestStatus = Literal[
    "pending",
    "assigned",
    "in_progress",
    "resolved",
]


RequestType = Literal[
    "evacuation",
    "transportation",
    "mobility_assistance",
    "medical_support",
    "rescue_support",
    "other",
]


AssistanceRequestSource = Literal[
    "manual",
    "decision_engine",
]


AccessibilityNeed = Literal[
    "mobility",
    "visual",
    "hearing",
    "cognitive",
]


# ============================================================
# ASSISTANCE REQUEST INPUT
# ============================================================

class AssistanceRequestInput(BaseModel):
    """
    Manual assistance request submitted to MONJED.

    System-generated requests triggered by the Decision Engine
    are created internally by the backend and carry additional
    traceability metadata in AssistanceRequestRecord.
    """

    zone_id: str = Field(
        min_length=1
    )

    location: str = Field(
        min_length=2
    )

    hazard: HazardType

    request_type: RequestType

    priority: RequestPriority

    description: str = Field(
        min_length=3,
        max_length=500,
    )


# ============================================================
# STORED ASSISTANCE REQUEST
# ============================================================

class AssistanceRequestRecord(BaseModel):
    """
    Stored assistance request.

    source identifies whether the request was submitted
    manually or generated by MONJED's deterministic
    Decision Engine.

    IMPORTANT:
    - A decision-engine request does not mean community
      evidence has been independently verified.
    - requires_trained_responder prevents safety-critical
      requests from being treated as ordinary volunteer tasks.
    """

    request_id: str

    zone_id: str

    location: str

    hazard: HazardType

    request_type: RequestType

    priority: RequestPriority

    description: str

    # --------------------------------------------------------
    # Request lifecycle
    # --------------------------------------------------------

    status: RequestStatus = "pending"

    assigned_volunteer_id: str | None = None

    # --------------------------------------------------------
    # Traceability
    # --------------------------------------------------------

    source: AssistanceRequestSource = "manual"

    decision_status: Literal[
        "human_review_required"
    ] | None = None

    evidence_used: int = Field(
        default=0,
        ge=0,
    )

    source_report_ids: list[str] = Field(
        default_factory=list
    )

    # --------------------------------------------------------
    # Safety / accessibility
    # --------------------------------------------------------

    accessibility_needs: list[
        AccessibilityNeed
    ] = Field(
        default_factory=list
    )

    requires_trained_responder: bool = False

    # --------------------------------------------------------
    # Timestamps
    # --------------------------------------------------------

    created_at: datetime

    assigned_at: datetime | None = None

    started_at: datetime | None = None

    resolved_at: datetime | None = None