from typing import Literal

from pydantic import BaseModel, Field


# ============================================================
# TYPES
# ============================================================

VolunteerSkill = Literal[
    "evacuation",
    "transportation",
    "mobility_assistance",
    "medical_support",
    "rescue_support",
    "general_support",
]


ResponderLevel = Literal[
    "volunteer",
    "trained_responder",
]


# ============================================================
# VOLUNTEER INPUT
# ============================================================

class VolunteerInput(BaseModel):
    """
    Person available to support MONJED assistance requests.

    IMPORTANT:
    responder_level is safety-critical.

    A normal volunteer must NOT be matched to requests that
    require a trained responder, such as rescue situations
    involving trapped people or dangerous structural damage.
    """

    name: str = Field(
        min_length=2,
        max_length=100,
    )

    zone_id: str = Field(
        min_length=1
    )

    available: bool = True

    # --------------------------------------------------------
    # RESPONDER SAFETY LEVEL
    # --------------------------------------------------------

    responder_level: ResponderLevel = "volunteer"

    # --------------------------------------------------------
    # TRANSPORT CAPABILITY
    # --------------------------------------------------------

    vehicle_type: str | None = Field(
        default=None,
        max_length=100,
    )

    capacity: int = Field(
        default=1,
        ge=1,
        le=100,
    )

    # --------------------------------------------------------
    # VERIFIED / DECLARED CAPABILITIES
    # --------------------------------------------------------

    skills: list[VolunteerSkill] = Field(
        default_factory=list
    )


# ============================================================
# STORED VOLUNTEER
# ============================================================

class VolunteerRecord(VolunteerInput):
    """
    Stored volunteer/responder record.

    volunteer_id is generated by the backend.
    """

    volunteer_id: str